### ISSUE TITLE
Virus in the file

### ISSUE THREAD

**Issue by Sn3akr** [Zodsmar/Amidst-Seed-Hunter-1.13#1]
Trojan:Win32/Occamy.C is a pretty shitty thing to get on to your PC... Stay away from this thing till it gets fixed or look for a different program!

**Comment by Red3Tango** [comment]
I can confirm this is a false-positive, it is an issue with the AutoIT script language. Some script-kiddies have made questionable programs with AutoIT which has gotten anything made with it flagged.

AutoIT is a very powerful program and _can_ be used for malicious purposes, I have gone through the source code and compiled myself to verify it is a false-positive.

**Comment by Zodsmar** [comment]
^ That
